// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Organized.Infrastructure.Database;

#nullable disable

namespace Organized.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260420211427_AddAchievementIsHidden")]
    partial class AddAchievementIsHidden
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Organized.Domain.Entities.Achievements.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden");

                    b.Property<int>("MaxProgress")
                        .HasColumnType("integer")
                        .HasColumnName("max_progress");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("achievements", "public");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Description = "Make your first table reservation",
                            IsHidden = false,
                            MaxProgress = 1,
                            Name = "First Reservation"
                        },
                        new
                        {
                            Id = 101,
                            Description = "Make 5 reservations",
                            IsHidden = false,
                            MaxProgress = 5,
                            Name = "Regular"
                        },
                        new
                        {
                            Id = 102,
                            Description = "Make 10 reservations",
                            IsHidden = false,
                            MaxProgress = 10,
                            Name = "Frequent Visitor"
                        },
                        new
                        {
                            Id = 103,
                            Description = "Make 25 reservations",
                            IsHidden = false,
                            MaxProgress = 25,
                            Name = "Power User"
                        },
                        new
                        {
                            Id = 104,
                            Description = "Make 50 reservations",
                            IsHidden = false,
                            MaxProgress = 50,
                            Name = "Legend"
                        },
                        new
                        {
                            Id = 105,
                            Description = "Make a reservation before 9 AM",
                            IsHidden = false,
                            MaxProgress = 1,
                            Name = "Early Bird"
                        },
                        new
                        {
                            Id = 106,
                            Description = "Make a reservation after 6 PM",
                            IsHidden = false,
                            MaxProgress = 1,
                            Name = "Night Owl"
                        },
                        new
                        {
                            Id = 107,
                            Description = "Reserve tables at 5 different companies",
                            IsHidden = false,
                            MaxProgress = 5,
                            Name = "Explorer"
                        },
                        new
                        {
                            Id = 108,
                            Description = "Add 10 friends",
                            IsHidden = false,
                            MaxProgress = 10,
                            Name = "Social Butterfly"
                        },
                        new
                        {
                            Id = 109,
                            Description = "Add 25 friends",
                            IsHidden = false,
                            MaxProgress = 25,
                            Name = "Networking Pro"
                        });
                });

            modelBuilder.Entity("Organized.Domain.Entities.Achievements.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("integer")
                        .HasColumnName("achievement_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "AchievementId")
                        .IsUnique();

                    b.ToTable("user_achievements", "public");
                });

            modelBuilder.Entity("Organized.Domain.Entities.Friends.FriendRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer")
                        .HasColumnName("receiver_id");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("friend_requests", "public");
                });

            modelBuilder.Entity("Organized.Domain.Entities.Friends.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FriendId")
                        .HasColumnType("integer")
                        .HasColumnName("friend_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "FriendId")
                        .IsUnique();

                    b.ToTable("friendships", "public");
                });

            modelBuilder.Entity("Organized.Domain.Entities.Reservations.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reservation_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TableId")
                        .HasColumnType("integer")
                        .HasColumnName("table_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ReservationDate");

                    b.HasIndex("TableId");

                    b.HasIndex("UserId");

                    b.ToTable("reservations", "public");
                });

            modelBuilder.Entity("Organized.Domain.Entities.Tables.CompanyTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.HasKey("Id");

                    b.ToTable("company_tables", "public");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            City = "New York",
                            CompanyName = "TechCorp"
                        },
                        new
                        {
                            Id = 101,
                            City = "New York",
                            CompanyName = "TechCorp"
                        },
                        new
                        {
                            Id = 102,
                            City = "Los Angeles",
                            CompanyName = "TechCorp"
                        },
                        new
                        {
                            Id = 103,
                            City = "Chicago",
                            CompanyName = "DataSoft"
                        },
                        new
                        {
                            Id = 104,
                            City = "Chicago",
                            CompanyName = "DataSoft"
                        },
                        new
                        {
                            Id = 105,
                            City = "Seattle",
                            CompanyName = "CloudBase"
                        },
                        new
                        {
                            Id = 106,
                            City = "Seattle",
                            CompanyName = "CloudBase"
                        },
                        new
                        {
                            Id = 107,
                            City = "Austin",
                            CompanyName = "InnovateLab"
                        },
                        new
                        {
                            Id = 108,
                            City = "Austin",
                            CompanyName = "InnovateLab"
                        },
                        new
                        {
                            Id = 109,
                            City = "San Francisco",
                            CompanyName = "StartupHub"
                        });
                });

            modelBuilder.Entity("Organized.Domain.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastOnline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_online");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("users", "public");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Email = "admin@organized.com",
                            LastOnline = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Admin User",
                            Password = "admin123"
                        },
                        new
                        {
                            Id = 101,
                            Email = "john.doe@example.com",
                            LastOnline = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "John Doe",
                            Password = "password123"
                        },
                        new
                        {
                            Id = 102,
                            Email = "jane.smith@example.com",
                            LastOnline = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Jane Smith",
                            Password = "password123"
                        },
                        new
                        {
                            Id = 103,
                            Email = "bob.johnson@example.com",
                            LastOnline = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bob Johnson",
                            Password = "password123"
                        },
                        new
                        {
                            Id = 104,
                            Email = "alice.brown@example.com",
                            LastOnline = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Alice Brown",
                            Password = "password123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
